#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

local_branch_name="$(git rev-parse --abbrev-ref HEAD)"
echo "Current branch is: $local_branch_name"

if [ $local_branch_name != "master" ]; then
  valid_branch_regex='^((e2e|fix|feat|hotfix|chore)\/[a-zA-Z0-9\-]+)$'
  message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

  if [[ ! $local_branch_name =~ $valid_branch_regex ]]; then
      echo "$message"
      exit 1
  fi
fi

npx lint-staged --relative